// Code generated by "stringer -type=GrowthClass"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[G_MEDIUM_FAST-0]
	_ = x[G_ERRATIC-1]
	_ = x[G_FLUCTUATING-2]
	_ = x[G_MEDIUM_SLOW-3]
	_ = x[G_FAST-4]
	_ = x[G_SLOW-5]
	_ = x[G_SLIGHT_FAST-16]
	_ = x[G_SLIGHT_SLOW-17]
}

const (
	_GrowthClass_name_0 = "G_MEDIUM_FASTG_ERRATICG_FLUCTUATINGG_MEDIUM_SLOWG_FASTG_SLOW"
	_GrowthClass_name_1 = "G_SLIGHT_FASTG_SLIGHT_SLOW"
)

var (
	_GrowthClass_index_0 = [...]uint8{0, 13, 22, 35, 48, 54, 60}
	_GrowthClass_index_1 = [...]uint8{0, 13, 26}
)

func (i GrowthClass) String() string {
	switch {
	case 0 <= i && i <= 5:
		return _GrowthClass_name_0[_GrowthClass_index_0[i]:_GrowthClass_index_0[i+1]]
	case 16 <= i && i <= 17:
		i -= 16
		return _GrowthClass_name_1[_GrowthClass_index_1[i]:_GrowthClass_index_1[i+1]]
	default:
		return "GrowthClass(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
